# Generated by Django 2.0.6 on 2018-06-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20180602_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
