const SUCCESS = 200;
const CREATED = 201;
const DELETED = 202;
const MODIFIED = 204;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const USER_ERROR = 422;
const SERVER_ERROR = 500;

module.exports = {
  SUCCESS,
  CREATED,
  MODIFIED,
  DELETED,
  UNAUTHORIZED,
  FORBIDDEN,
  USER_ERROR,
  SERVER_ERROR,
};
