# Generated by Django 2.1.2 on 2018-11-07 03:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndbno', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('measure', models.CharField(max_length=100)),
                ('nutrients', models.CharField(max_length=100)),
                ('nutrient_id', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('gm', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'ingredients',
                'db_table': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('RecipeID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CookTime', models.DurationField()),
                ('CookingMethod', models.CharField(max_length=50)),
                ('Nutrition', models.CharField(max_length=100)),
                ('RecipeTitle', models.CharField(blank=True, max_length=50)),
                ('RecipeCategory', models.CharField(max_length=50)),
                ('RecipeCuisine', models.CharField(max_length=50)),
                ('RecipeInstructions', models.TextField()),
                ('RecipeYield', models.IntegerField()),
                ('SuitableForDiet', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('RecipeIngredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DET_App.Ingredients')),
            ],
            options={
                'verbose_name_plural': 'recipes',
                'db_table': 'Recipe',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('UserEmail', models.CharField(max_length=256, unique=True)),
                ('Username', models.CharField(max_length=50)),
                ('UserFirstName', models.CharField(blank=True, max_length=50)),
                ('UserLastName', models.CharField(blank=True, max_length=50)),
                ('UserPW', models.CharField(max_length=256)),
                ('CustomerID', models.CharField(blank=True, max_length=256)),
                ('Subscription', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'user',
                'db_table': 'User',
            },
        ),
    ]
