# Generated by Django 2.1.2 on 2018-11-06 00:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DET_App', '0002_auto_20181101_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Username',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
