'''
dbname – the database name (database is a deprecated alias)
user – user name used to authenticate
password – password used to authenticate
host – database host address (defaults to UNIX socket if not provided)
port – connection port number (defaults to 5432 if not provided)

'''
import psycopg2
from dotenv import load_dotenv, find_dotenv
from settings import DB_NAME, DB_USERNAME, DB_PASSWORD, DB_HOST
import pandas as pd 
import numpy as np
from urllib.request import urlretrieve

REMOVE_COLS = ['scrape_id','last_scraped','smart_location','calendar_last_scraped']
HOST_COLS = ['host_id','host_url','host_name','host_since',
'host_location','host_about','host_response_time','host_response_rate',
'host_acceptance_rate','host_is_superhost','host_thumbnail_url',
'host_picture_url','host_neighbourhood','host_listings_count',
'host_total_listings_count','host_verifications',
'host_has_profile_pic','host_identity_verified']

lists = ['http://data.insideairbnb.com/united-states/nc/asheville/2019-07-25/data/listings.csv',
 'http://data.insideairbnb.com/united-states/nc/asheville/2019-06-26/data/listings.csv',
 'http://data.insideairbnb.com/united-states/nc/asheville/2019-05-26/data/listings.csv',
 'http://data.insideairbnb.com/united-states/nc/asheville/2019-04-23/data/listings.csv',
 'http://data.insideairbnb.com/united-states/nc/asheville/2019-03-25/data/listings.csv',
 'http://data.insideairbnb.com/united-states/nc/asheville/2019-02-17/data/listings.csv',
 'http://data.insideairbnb.com/united-states/nc/asheville/2019-01-27/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/nc/asheville/2018-12-16/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/nc/asheville/2018-11-20/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/nc/asheville/2018-10-17/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/nc/asheville/2018-09-16/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/nc/asheville/2018-08-21/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/nc/asheville/2018-07-29/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/nc/asheville/2018-04-18/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/nc/asheville/2016-04-18/data/listings.csv',
 'http://data.insideairbnb.com/united-states/tx/austin/2019-07-12/data/listings.csv',
 'http://data.insideairbnb.com/united-states/tx/austin/2019-06-08/data/listings.csv',
 'http://data.insideairbnb.com/united-states/tx/austin/2019-05-14/data/listings.csv',
 'http://data.insideairbnb.com/united-states/tx/austin/2019-04-11/data/listings.csv',
 'http://data.insideairbnb.com/united-states/tx/austin/2019-03-08/data/listings.csv',
 'http://data.insideairbnb.com/united-states/tx/austin/2019-02-06/data/listings.csv',
 'http://data.insideairbnb.com/united-states/tx/austin/2019-01-14/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/tx/austin/2018-12-10/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/tx/austin/2018-11-12/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/tx/austin/2018-10-18/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/tx/austin/2018-09-12/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/tx/austin/2018-08-14/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/tx/austin/2018-07-10/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/tx/austin/2018-05-14/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/tx/austin/2018-04-12/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/tx/austin/2017-03-07/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/tx/austin/2015-11-07/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/tx/austin/2015-05-23/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ma/boston/2019-07-14/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ma/boston/2019-06-14/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ma/boston/2019-05-19/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ma/boston/2019-04-15/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ma/boston/2019-03-12/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ma/boston/2019-02-09/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ma/boston/2019-01-17/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ma/boston/2018-12-13/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ma/boston/2018-11-17/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ma/boston/2018-10-11/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ma/boston/2018-09-14/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ma/boston/2018-08-17/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ma/boston/2018-07-18/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ma/boston/2018-05-17/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ma/boston/2018-04-14/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ma/boston/2017-10-06/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ma/boston/2016-09-07/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ma/boston/2015-10-03/data/listings.csv',
 'http://data.insideairbnb.com/united-states/fl/broward-county/2019-08-18/data/listings.csv',
 'http://data.insideairbnb.com/united-states/fl/broward-county/2019-07-14/data/listings.csv',
 'http://data.insideairbnb.com/united-states/fl/broward-county/2019-06-13/data/listings.csv',
 'http://data.insideairbnb.com/united-states/fl/broward-county/2019-05-19/data/listings.csv',
 'http://data.insideairbnb.com/united-states/fl/broward-county/2019-04-15/data/listings.csv',
 'http://data.insideairbnb.com/united-states/fl/broward-county/2019-03-11/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ma/cambridge/2019-08-28/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ma/cambridge/2019-07-20/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ma/cambridge/2019-06-24/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ma/cambridge/2019-05-23/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ma/cambridge/2019-04-18/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ma/cambridge/2019-03-18/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ma/cambridge/2019-02-13/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ma/cambridge/2019-01-22/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ma/cambridge/2018-12-15/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ma/cambridge/2018-11-18/data/listings.csv',
 'http://data.insideairbnb.com/united-states/il/chicago/2019-07-15/data/listings.csv',
 'http://data.insideairbnb.com/united-states/il/chicago/2019-06-14/data/listings.csv',
 'http://data.insideairbnb.com/united-states/il/chicago/2019-05-19/data/listings.csv',
 'http://data.insideairbnb.com/united-states/il/chicago/2019-04-15/data/listings.csv',
 'http://data.insideairbnb.com/united-states/il/chicago/2019-03-12/data/listings.csv',
 'http://data.insideairbnb.com/united-states/il/chicago/2019-02-09/data/listings.csv',
 'http://data.insideairbnb.com/united-states/il/chicago/2019-01-17/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/il/chicago/2018-12-13/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/il/chicago/2018-11-15/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/il/chicago/2018-10-11/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/il/chicago/2018-09-14/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/il/chicago/2018-08-17/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/il/chicago/2018-07-18/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/il/chicago/2018-05-18/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/il/chicago/2018-04-15/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/il/chicago/2017-05-10/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/il/chicago/2015-10-03/data/listings.csv',
 'http://data.insideairbnb.com/united-states/nv/clark-county-nv/2019-08-28/data/listings.csv',
 'http://data.insideairbnb.com/united-states/nv/clark-county-nv/2019-07-20/data/listings.csv',
 'http://data.insideairbnb.com/united-states/nv/clark-county-nv/2019-06-25/data/listings.csv',
 'http://data.insideairbnb.com/united-states/nv/clark-county-nv/2019-05-23/data/listings.csv',
 'http://data.insideairbnb.com/united-states/nv/clark-county-nv/2019-04-20/data/listings.csv',
 'http://data.insideairbnb.com/united-states/nv/clark-county-nv/2019-03-18/data/listings.csv',
 'http://data.insideairbnb.com/united-states/nv/clark-county-nv/2019-02-13/data/listings.csv',
 'http://data.insideairbnb.com/united-states/nv/clark-county-nv/2019-01-22/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/nv/clark-county-nv/2018-12-15/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/nv/clark-county-nv/2018-11-18/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/nv/clark-county-nv/2018-10-25/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/nv/clark-county-nv/2018-09-10/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/nv/clark-county-nv/2018-08-06/data/listings.csv',
 'http://data.insideairbnb.com/united-states/oh/columbus/2019-08-19/data/listings.csv',
 'http://data.insideairbnb.com/united-states/oh/columbus/2019-07-14/data/listings.csv',
 'http://data.insideairbnb.com/united-states/oh/columbus/2019-06-14/data/listings.csv',
 'http://data.insideairbnb.com/united-states/oh/columbus/2019-05-18/data/listings.csv',
 'http://data.insideairbnb.com/united-states/oh/columbus/2019-04-15/data/listings.csv',
 'http://data.insideairbnb.com/united-states/oh/columbus/2019-03-12/data/listings.csv',
 'http://data.insideairbnb.com/united-states/oh/columbus/2019-02-09/data/listings.csv',
 'http://data.insideairbnb.com/united-states/oh/columbus/2019-01-17/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/oh/columbus/2018-12-13/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/oh/columbus/2018-11-17/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/oh/columbus/2018-10-11/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/oh/columbus/2018-09-14/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/oh/columbus/2018-08-16/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/oh/columbus/2018-07-17/data/listings.csv',
 'http://data.insideairbnb.com/united-states/co/denver/2019-07-28/data/listings.csv',
 'http://data.insideairbnb.com/united-states/co/denver/2019-06-29/data/listings.csv',
 'http://data.insideairbnb.com/united-states/co/denver/2019-05-29/data/listings.csv',
 'http://data.insideairbnb.com/united-states/co/denver/2019-04-27/data/listings.csv',
 'http://data.insideairbnb.com/united-states/co/denver/2019-03-28/data/listings.csv',
 'http://data.insideairbnb.com/united-states/co/denver/2019-02-18/data/listings.csv',
 'http://data.insideairbnb.com/united-states/co/denver/2019-01-29/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/co/denver/2018-12-21/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/co/denver/2018-11-22/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/co/denver/2018-10-18/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/co/denver/2018-09-21/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/co/denver/2018-08-27/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/co/denver/2018-07-31/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/co/denver/2018-04-21/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/co/denver/2017-11-24/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/co/denver/2016-05-16/data/listings.csv',
 'http://data.insideairbnb.com/united-states/hi/hawaii/2019-08-06/data/listings.csv',
 'http://data.insideairbnb.com/united-states/hi/hawaii/2019-07-08/data/listings.csv',
 'http://data.insideairbnb.com/united-states/hi/hawaii/2019-06-03/data/listings.csv',
 'http://data.insideairbnb.com/united-states/hi/hawaii/2019-05-03/data/listings.csv',
 'http://data.insideairbnb.com/united-states/hi/hawaii/2019-04-03/data/listings.csv',
 'http://data.insideairbnb.com/united-states/hi/hawaii/2019-03-06/data/listings.csv',
 'http://data.insideairbnb.com/united-states/hi/hawaii/2019-02-02/data/listings.csv',
 'http://data.insideairbnb.com/united-states/hi/hawaii/2019-01-09/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/hi/hawaii/2018-12-06/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/hi/hawaii/2018-11-03/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/hi/hawaii/2018-10-03/data/listings.csv',
 'http://data.insideairbnb.com/united-states/nj/jersey-city/2019-08-31/data/listings.csv',
 'http://data.insideairbnb.com/united-states/nj/jersey-city/2019-07-29/data/listings.csv',
 'http://data.insideairbnb.com/united-states/nj/jersey-city/2019-06-29/data/listings.csv',
 'http://data.insideairbnb.com/united-states/nj/jersey-city/2019-05-29/data/listings.csv',
 'http://data.insideairbnb.com/united-states/nj/jersey-city/2019-04-27/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/los-angeles/2019-07-08/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/los-angeles/2019-06-04/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/los-angeles/2019-05-05/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/los-angeles/2019-04-05/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/los-angeles/2019-03-06/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/los-angeles/2019-02-03/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/los-angeles/2019-01-11/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/los-angeles/2018-12-06/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/los-angeles/2018-11-04/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/los-angeles/2018-10-05/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/los-angeles/2018-09-08/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/los-angeles/2018-08-07/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/los-angeles/2018-07-05/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/los-angeles/2018-06-06/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/los-angeles/2018-05-09/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/los-angeles/2018-04-07/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/los-angeles/2017-05-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/los-angeles/2017-04-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/los-angeles/2017-03-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/los-angeles/2016-08-03/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/los-angeles/2016-07-03/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/los-angeles/2016-05-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/los-angeles/2016-01-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/los-angeles/2015-11-06/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/los-angeles/2015-09-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/los-angeles/2015-07-25/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/los-angeles/2015-05-24/data/listings.csv',
 'http://data.insideairbnb.com/united-states/tn/nashville/2019-07-13/data/listings.csv',
 'http://data.insideairbnb.com/united-states/tn/nashville/2019-06-11/data/listings.csv',
 'http://data.insideairbnb.com/united-states/tn/nashville/2019-05-15/data/listings.csv',
 'http://data.insideairbnb.com/united-states/tn/nashville/2019-04-14/data/listings.csv',
 'http://data.insideairbnb.com/united-states/tn/nashville/2019-03-11/data/listings.csv',
 'http://data.insideairbnb.com/united-states/tn/nashville/2019-02-09/data/listings.csv',
 'http://data.insideairbnb.com/united-states/tn/nashville/2019-01-17/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/tn/nashville/2018-12-12/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/tn/nashville/2018-11-15/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/tn/nashville/2018-10-11/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/tn/nashville/2018-09-13/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/tn/nashville/2018-08-16/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/tn/nashville/2018-07-13/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/tn/nashville/2018-05-17/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/tn/nashville/2018-04-14/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/tn/nashville/2017-09-14/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/tn/nashville/2016-09-06/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/tn/nashville/2015-10-03/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/tn/nashville/2015-09-05/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/tn/nashville/2015-06-22/data/listings.csv',
 'http://data.insideairbnb.com/united-states/la/new-orleans/2019-08-08/data/listings.csv',
 'http://data.insideairbnb.com/united-states/la/new-orleans/2019-07-08/data/listings.csv',
 'http://data.insideairbnb.com/united-states/la/new-orleans/2019-06-03/data/listings.csv',
 'http://data.insideairbnb.com/united-states/la/new-orleans/2019-05-05/data/listings.csv',
 'http://data.insideairbnb.com/united-states/la/new-orleans/2019-04-05/data/listings.csv',
 'http://data.insideairbnb.com/united-states/la/new-orleans/2019-03-06/data/listings.csv',
 'http://data.insideairbnb.com/united-states/la/new-orleans/2019-02-03/data/listings.csv',
 'http://data.insideairbnb.com/united-states/la/new-orleans/2019-01-11/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2018-12-06/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2018-11-04/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2018-10-05/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2018-09-08/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2018-08-07/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2018-07-05/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2018-05-09/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2018-04-07/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2018-03-06/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2018-02-03/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2018-01-11/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2017-12-04/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2017-11-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2017-10-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2017-09-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2017-08-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2017-07-03/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2017-06-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2017-05-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2017-04-10/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2017-04-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2017-03-04/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2017-02-05/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2017-01-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2016-12-05/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2016-11-03/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2016-10-03/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2016-09-04/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2016-08-04/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2016-07-04/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2016-06-03/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2016-05-03/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2016-04-05/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2016-02-03/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2015-09-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/la/new-orleans/2015-06-05/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ny/new-york-city/2019-08-06/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ny/new-york-city/2019-07-08/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ny/new-york-city/2019-06-02/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ny/new-york-city/2019-05-03/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ny/new-york-city/2019-04-03/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ny/new-york-city/2019-03-06/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ny/new-york-city/2019-02-01/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ny/new-york-city/2019-01-09/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2018-12-06/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2018-11-03/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2018-10-03/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2018-09-08/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2018-08-06/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2018-07-05/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2018-06-03/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2018-05-09/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2018-04-06/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2018-03-04/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2018-02-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2018-01-10/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2018-01-10/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2017-12-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2017-11-01/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2017-10-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2017-09-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2017-08-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2017-07-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2017-06-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2017-05-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2017-04-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2017-03-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2017-02-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2017-01-01/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2016-12-03/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2016-11-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2016-10-01/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2016-09-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2016-08-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2016-07-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2016-06-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2016-05-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2016-04-03/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2016-02-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2016-01-01/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2015-12-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2015-11-20/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2015-11-01/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2015-10-01/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2015-09-01/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2015-08-01/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2015-06-01/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2015-05-01/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2015-03-01/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ny/new-york-city/2015-01-01/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/oakland/2019-07-13/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/oakland/2019-06-13/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/oakland/2019-05-18/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/oakland/2019-04-14/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/oakland/2019-03-11/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/oakland/2019-02-09/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/oakland/2019-01-17/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/oakland/2018-12-12/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/oakland/2018-11-15/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/oakland/2018-10-11/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/oakland/2018-09-13/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/oakland/2018-08-16/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/oakland/2018-07-16/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/oakland/2018-05-17/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/oakland/2018-04-14/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/oakland/2016-05-04/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/oakland/2015-06-22/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/pacific-grove/2019-07-31/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/pacific-grove/2019-07-01/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/pacific-grove/2019-05-31/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/pacific-grove/2019-05-01/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/pacific-grove/2019-03-31/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/pacific-grove/2019-02-26/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/pacific-grove/2019-01-31/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/pacific-grove/2018-12-22/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/pacific-grove/2018-11-27/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/pacific-grove/2018-10-25/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/pacific-grove/2018-09-29/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/pacific-grove/2018-08-30/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/pacific-grove/2018-07-31/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/pacific-grove/2018-04-22/data/listings.csv',
 'http://data.insideairbnb.com/united-states/or/portland/2019-07-10/data/listings.csv',
 'http://data.insideairbnb.com/united-states/or/portland/2019-06-07/data/listings.csv',
 'http://data.insideairbnb.com/united-states/or/portland/2019-05-13/data/listings.csv',
 'http://data.insideairbnb.com/united-states/or/portland/2019-04-10/data/listings.csv',
 'http://data.insideairbnb.com/united-states/or/portland/2019-03-08/data/listings.csv',
 'http://data.insideairbnb.com/united-states/or/portland/2019-02-06/data/listings.csv',
 'http://data.insideairbnb.com/united-states/or/portland/2019-01-13/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2018-12-10/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2018-11-07/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2018-10-09/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2018-09-14/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2018-08-14/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2018-07-10/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2018-05-13/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2018-04-11/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2018-02-08/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2018-01-16/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2017-12-09/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2017-11-13/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2017-10-04/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2017-09-12/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2017-08-06/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2017-07-06/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2017-06-05/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2017-05-07/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2017-04-07/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2017-03-05/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2017-02-09/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2017-01-04/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2016-12-08/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2016-11-06/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2016-10-03/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2016-09-04/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2016-08-04/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2016-07-04/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2016-06-03/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2016-05-03/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2016-04-05/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2016-02-03/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2016-01-01/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2015-12-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2015-11-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2015-10-01/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2015-09-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2015-05-12/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/portland/2015-03-01/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ri/rhode-island/2019-07-30/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ri/rhode-island/2019-06-30/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ri/rhode-island/2019-05-30/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ri/rhode-island/2019-04-30/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ri/rhode-island/2019-03-31/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ri/rhode-island/2019-02-19/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ri/rhode-island/2019-01-30/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ri/rhode-island/2018-12-22/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ri/rhode-island/2018-11-27/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ri/rhode-island/2018-10-21/data/listings.csv',
 'http://data.insideairbnb.com/united-states/or/salem-or/2019-08-17/data/listings.csv',
 'http://data.insideairbnb.com/united-states/or/salem-or/2019-07-09/data/listings.csv',
 'http://data.insideairbnb.com/united-states/or/salem-or/2019-06-06/data/listings.csv',
 'http://data.insideairbnb.com/united-states/or/salem-or/2019-05-11/data/listings.csv',
 'http://data.insideairbnb.com/united-states/or/salem-or/2019-04-09/data/listings.csv',
 'http://data.insideairbnb.com/united-states/or/salem-or/2019-03-07/data/listings.csv',
 'http://data.insideairbnb.com/united-states/or/salem-or/2019-02-05/data/listings.csv',
 'http://data.insideairbnb.com/united-states/or/salem-or/2019-01-14/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/salem-or/2018-12-08/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/salem-or/2018-11-17/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/salem-or/2018-10-18/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/salem-or/2018-09-11/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/or/salem-or/2018-08-10/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/san-diego/2019-08-18/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/san-diego/2019-07-14/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/san-diego/2019-06-13/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/san-diego/2019-05-18/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/san-diego/2019-04-15/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/san-diego/2019-03-11/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/san-diego/2019-02-09/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/san-diego/2019-01-17/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-diego/2018-12-13/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-diego/2018-11-15/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-diego/2018-10-11/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-diego/2018-09-13/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-diego/2018-08-16/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-diego/2018-07-16/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-diego/2018-05-17/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-diego/2018-04-14/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-diego/2016-07-07/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-diego/2015-06-22/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/san-francisco/2019-08-06/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/san-francisco/2019-07-08/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/san-francisco/2019-06-02/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/san-francisco/2019-05-03/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/san-francisco/2019-04-03/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/san-francisco/2019-03-06/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/san-francisco/2019-02-01/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/san-francisco/2019-01-09/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2018-12-06/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2018-11-03/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2018-10-03/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2018-09-08/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2018-08-06/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2018-07-05/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2018-05-09/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2018-04-06/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2018-03-04/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2018-02-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2018-01-17/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2018-01-10/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2017-12-07/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2017-12-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2017-11-08/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2017-11-01/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2017-10-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2017-09-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2017-08-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2017-07-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2017-06-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2017-05-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2017-04-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2017-03-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2017-02-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2017-01-01/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2016-12-03/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2016-11-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2016-10-01/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2016-09-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2016-08-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2016-07-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2016-06-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2016-05-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2016-04-03/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2016-02-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2015-12-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2015-11-01/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2015-09-02/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/san-francisco/2015-05-04/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/san-mateo-county/2019-06-05/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/santa-clara-county/2019-07-09/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/santa-clara-county/2019-06-06/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/santa-clara-county/2019-05-13/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/santa-clara-county/2019-04-09/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/santa-clara-county/2019-03-07/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/santa-clara-county/2019-02-05/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/santa-clara-county/2019-01-14/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/santa-clara-county/2018-12-08/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/santa-clara-county/2018-11-17/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/santa-clara-county/2018-10-18/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/santa-clara-county/2018-09-10/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/santa-clara-county/2018-08-14/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/santa-clara-county/2018-07-07/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/santa-cruz-county/2019-07-30/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/santa-cruz-county/2019-06-30/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/santa-cruz-county/2019-05-30/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/santa-cruz-county/2019-04-30/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/santa-cruz-county/2019-03-30/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/santa-cruz-county/2019-02-19/data/listings.csv',
 'http://data.insideairbnb.com/united-states/ca/santa-cruz-county/2019-01-30/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/santa-cruz-county/2018-12-22/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/santa-cruz-county/2018-11-26/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/santa-cruz-county/2018-10-20/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/santa-cruz-county/2018-09-28/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/santa-cruz-county/2018-08-30/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/santa-cruz-county/2018-07-31/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/santa-cruz-county/2018-04-22/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/ca/santa-cruz-county/2015-10-15/data/listings.csv',
 'http://data.insideairbnb.com/united-states/wa/seattle/2019-08-18/data/listings.csv',
 'http://data.insideairbnb.com/united-states/wa/seattle/2019-07-14/data/listings.csv',
 'http://data.insideairbnb.com/united-states/wa/seattle/2019-06-13/data/listings.csv',
 'http://data.insideairbnb.com/united-states/wa/seattle/2019-05-18/data/listings.csv',
 'http://data.insideairbnb.com/united-states/wa/seattle/2019-04-15/data/listings.csv',
 'http://data.insideairbnb.com/united-states/wa/seattle/2019-03-11/data/listings.csv',
 'http://data.insideairbnb.com/united-states/wa/seattle/2019-02-09/data/listings.csv',
 'http://data.insideairbnb.com/united-states/wa/seattle/2019-01-17/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/wa/seattle/2018-12-13/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/wa/seattle/2018-11-15/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/wa/seattle/2018-10-11/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/wa/seattle/2018-09-14/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/wa/seattle/2018-08-16/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/wa/seattle/2018-07-17/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/wa/seattle/2018-05-17/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/wa/seattle/2018-04-14/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/wa/seattle/2016-01-04/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/wa/seattle/2015-06-22/data/listings.csv',
 'http://data.insideairbnb.com/united-states/mn/twin-cities-msa/2019-08-06/data/listings.csv',
 'http://data.insideairbnb.com/united-states/mn/twin-cities-msa/2019-07-08/data/listings.csv',
 'http://data.insideairbnb.com/united-states/mn/twin-cities-msa/2019-06-02/data/listings.csv',
 'http://data.insideairbnb.com/united-states/mn/twin-cities-msa/2019-05-05/data/listings.csv',
 'http://data.insideairbnb.com/united-states/mn/twin-cities-msa/2019-04-03/data/listings.csv',
 'http://data.insideairbnb.com/united-states/mn/twin-cities-msa/2019-03-06/data/listings.csv',
 'http://data.insideairbnb.com/united-states/mn/twin-cities-msa/2019-02-01/data/listings.csv',
 'http://data.insideairbnb.com/united-states/mn/twin-cities-msa/2019-01-10/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/mn/twin-cities-msa/2018-12-06/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/mn/twin-cities-msa/2018-11-03/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/mn/twin-cities-msa/2018-10-03/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/mn/twin-cities-msa/2018-09-08/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/mn/twin-cities-msa/2018-08-06/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/mn/twin-cities-msa/2018-07-05/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/mn/twin-cities-msa/2018-05-09/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/mn/twin-cities-msa/2018-04-07/data/listings.csv',
 'http://data.insideairbnb.com/united-states/dc/washington-dc/2019-07-15/data/listings.csv',
 'http://data.insideairbnb.com/united-states/dc/washington-dc/2019-06-16/data/listings.csv',
 'http://data.insideairbnb.com/united-states/dc/washington-dc/2019-05-20/data/listings.csv',
 'http://data.insideairbnb.com/united-states/dc/washington-dc/2019-04-15/data/listings.csv',
 'http://data.insideairbnb.com/united-states/dc/washington-dc/2019-03-12/data/listings.csv',
 'http://data.insideairbnb.com/united-states/dc/washington-dc/2019-02-11/data/listings.csv',
 'http://data.insideairbnb.com/united-states/dc/washington-dc/2019-01-17/data/listings.csv']
#  'http://data.insideairbnb.com/united-states/dc/washington-dc/2018-12-13/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/dc/washington-dc/2018-11-15/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/dc/washington-dc/2018-10-12/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/dc/washington-dc/2018-09-14/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/dc/washington-dc/2018-08-18/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/dc/washington-dc/2018-07-20/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/dc/washington-dc/2018-05-18/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/dc/washington-dc/2018-04-15/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/dc/washington-dc/2017-05-10/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/dc/washington-dc/2017-03-10/data/listings.csv',
#  'http://data.insideairbnb.com/united-states/dc/washington-dc/2015-10-03/data/listings.csv']


def series_to_bool(series):
    series = series.replace('t',True).replace('f',False)
    return series


def clean_strs(series):
    series = series.str.strip('$').str.replace(',','')
    return series.astype(float)

i = 191
while i < len(lists):

    url = urlretrieve(lists[i],f'l{i}.csv')
    listing = pd.read_csv(f'l{i}.csv')
    listing = listing.drop(REMOVE_COLS,axis=1)
    listing = listing.drop(HOST_COLS,axis=1)
    listing.rename(columns={'listing_url':'url'},inplace=True)
    listing['zipcode'] = (listing['zipcode'].str.split('\n',expand=True)[0]).str.split('-',expand=True)[0]
    #listing['zipcode'] = (listing['zipcode'].str.split('NY ',expand=True)[1])
    listing['neighbourhood'] = 0
    listing['neighbourhood_cleansed'] = 0 
    listing['neighbourhood_group_cleansed'] = 0 
    listing = listing.loc[(listing['zipcode'] != ' ') & (listing['zipcode'] != 'CA')]
    listing['zipcode'] = listing['zipcode'].replace('MN 55404','55404')
    listing['zipcode'] = listing['zipcode'].replace('CA 94158','94158')
    listing['zipcode'] = listing['zipcode'].replace('CA 94103','94103')
    listing['zipcode'] = listing['zipcode'].replace('CA 94108','94108')
    listing['zipcode'] = listing['zipcode'].replace('CA 94115','94115')
    listing['zipcode'] = listing['zipcode'].replace('CA 94109','94109')
    listing['zipcode'] = listing['zipcode'].replace('CA 94105','94105')
    listing['zipcode'] = listing['zipcode'].replace('CA 94102','94102')
    listing['zipcode'] = listing['zipcode'].replace('CA ',' ')
    listing['zipcode'] = listing['zipcode'].replace('',0)
    listing['zipcode'] = listing['zipcode'].fillna(0).astype(float)


    listing['is_location_exact'] = series_to_bool(listing['is_location_exact'])
    listing['require_guest_profile_picture'] = series_to_bool(listing['require_guest_profile_picture'])
    listing['require_guest_phone_verification'] = series_to_bool(listing['require_guest_phone_verification'])
    listing['is_business_travel_ready'] = series_to_bool(listing['is_business_travel_ready'])
    listing['has_availability'] = series_to_bool(listing['has_availability'])
    listing['requires_license'] = series_to_bool(listing['requires_license'])
    listing['instant_bookable'] = series_to_bool(listing['instant_bookable'])

    listing['price'] = clean_strs(listing['price'])
    listing['weekly_price'] = clean_strs(listing['weekly_price'])
    listing['monthly_price'] = clean_strs(listing['monthly_price'])
    listing['security_deposit'] = clean_strs(listing['security_deposit'])
    listing['extra_people'] = clean_strs(listing['extra_people'])
    listing['cleaning_fee'] = clean_strs(listing['cleaning_fee'])
    if listing['cleaning_fee'].dtype == 'object':
        listing['cleaning_fee'] = listing['cleaning_fee'].str.strip('$').str.strip(',').astype(float)
    listing.drop('license',axis=1,inplace=True)
    listing.drop('jurisdiction_names',axis=1,inplace=True)

    listing['neighbourhood'].fillna(0)
    listing['neighbourhood_group_cleansed'].fillna(0)
    listing['square_feet'].fillna(0)

    for col in listing.columns:
        if 'url' in col:
            listing[col] = listing[str(col)].astype(str)

    for col in listing.columns:
        if listing[str(col)].dtype == 'object':
            listing[col].fillna('',inplace=True)
            
        else:
            listing[str(col)].fillna(0,inplace=True)


    connection = psycopg2.connect(dbname="postgres", 
                            user="ridley", 
                            password="sAYD6HJETeGHy7a9", 
                            host='airbnb.c38lxrcn63qf.us-west-1.rds.amazonaws.com',
                            port=5432)
    cursor=connection.cursor()

    sql = """INSERT INTO listing (id,
                            url,
                            name,
                            summary,
                            space,
                            description,
                            experiences_offered,
                            neighborhood_overview,
                            notes,
                            transit,
                            access,
                            interaction,
                            house_rules,
                            thumbnail_url,
                            medium_url,
                            picture_url,
                            xl_picture_url,
                            street,
                            neighbourhood,
                            neighbourhood_cleansed,
                            neighbourhood_group_cleansed,
                            city,
                            state,
                            zipcode,
                            market,
                            country_code,
                            country,
                            latitude,
                            longitude,
                            is_location_exact,
                            property_type,
                            room_type,
                            accommodates,
                            bathrooms,
                            bedrooms,
                            beds,
                            bed_type,
                            amenities,
                            square_feet,
                            price,
                            weekly_price,
                            monthly_price,
                            security_deposit,
                            cleaning_fee,
                            guests_included,
                            extra_people,
                            minimum_nights,
                            maximum_nights,
                            minimum_minimum_nights,
                            maximum_minimum_nights,
                            minimum_maximum_nights,
                            maximum_maximum_nights,
                            minimum_nights_avg_ntm,
                            maximum_nights_avg_ntm,
                            calendar_updated,
                            has_availability,
                            availability_30,
                            availability_60,
                            availability_90,
                            availability_365,
                            number_of_reviews,
                            number_of_reviews_ltm,
                            first_review,
                            last_review,
                            review_scores_rating,
                            review_scores_accuracy,
                            review_scores_cleanliness,
                            review_scores_checkin,
                            review_scores_communication,
                            review_scores_location,
                            review_scores_value,
                            requires_license,
                            instant_bookable,
                            is_business_travel_ready,
                            cancellation_policy,
                            require_guest_profile_picture,
                            require_guest_phone_verification,
                            calculated_host_listings_count,
                            calculated_host_listings_count_entire_homes,
                            calculated_host_listings_count_private_rooms,
                            calculated_host_listings_count_shared_rooms,
                            reviews_per_month)
        VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"""


    master_list = []
    for row in listing.itertuples(index=False):
        master_list.append(row)
    if len(master_list) != 0:
        cursor.executemany(sql, master_list)
        connection.commit()
        cursor.close()
    i+=1