# Generated by Django 2.1.2 on 2018-11-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DET_App', '0003_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='Nutrition',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='CookTime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='RecipeIngredients',
            field=models.CharField(max_length=100),
        ),
    ]
