# Generated by Django 2.1.1 on 2018-09-26 17:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('man_type', models.CharField(max_length=200)),
                ('tail_number', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('license_type', models.CharField(choices=[('Airplane SEL', 'SEL'), ('Airplane SES', 'SES'), ('Airplane MEL', 'MEL'), ('Airplane MES', 'MES')], default='Airplane SEL', max_length=40)),
                ('photo', models.ImageField(blank=True, default='/plane.jpg', upload_to='aircrafts/%Y/%m/%D/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Aircraft',
            },
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_token', models.CharField(max_length=200)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('no_instument_app', models.FloatField(blank=True, default=0.0, null=True)),
                ('no_ldg', models.FloatField(blank=True, default=0.0, null=True)),
                ('cross_country', models.FloatField(blank=True, default=0.0, null=True)),
                ('pic', models.FloatField(blank=True, default=0.0, null=True)),
                ('dual_rec', models.FloatField(blank=True, default=0.0, null=True)),
                ('actual_instr', models.FloatField(blank=True, default=0.0, null=True)),
                ('sim_instr', models.FloatField(blank=True, default=0.0, null=True)),
                ('day', models.FloatField(blank=True, default=0.0, null=True)),
                ('night', models.FloatField(blank=True, default=0.0, null=True)),
                ('airports_visited', models.CharField(blank=True, default='Airports', max_length=100)),
                ('fly_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('snippet', models.TextField(blank=True, default='snippet', null=True)),
                ('license_type', models.CharField(default='Airplane SEL', max_length=40)),
                ('total_hours', models.FloatField(default=0.0)),
                ('sv_html', models.CharField(blank=True, max_length=300)),
                ('sv_script', models.CharField(blank=True, max_length=300)),
                ('aircraft', models.ForeignKey(default=uuid.uuid4, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.Aircraft')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'flights',
            },
        ),
        migrations.RemoveField(
            model_name='aircraftinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='flightsinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='AircraftInfo',
        ),
        migrations.DeleteModel(
            name='FlightsInfo',
        ),
    ]
