# Generated by Django 2.1.1 on 2018-10-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_auto_20180928_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='stripe_payment_token',
        ),
        migrations.AddField(
            model_name='billing',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
