# Generated by Django 2.1.1 on 2018-09-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='end_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_datetime',
            field=models.DateTimeField(),
        ),
    ]
