# Generated by Django 2.1.1 on 2018-09-20 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiftapp', '0002_auto_20180920_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shiftapp.Profile'),
        ),
    ]
