# Generated by Django 2.1.1 on 2018-09-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftapp', '0004_auto_20180920_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='notes',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='notes',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
