# Generated by Django 2.1.1 on 2018-10-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftapp', '0007_auto_20180926_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourofoperation',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
