# Uncomment the next line to define a global platform for your project

 platform :ios, '12.0'


target 'Future-Hope' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Future-Hope
	
	# Firebase
	
	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
	pod 'GoogleSignIn'
	
	pod 'FacebookCore'
	pod 'FacebookLogin'
	
	# Material Desing
	pod 'MaterialComponents/TextFields'
	pod 'MaterialComponents/Buttons'
	
	

end
