CREATE TABLE listing(
  id NUMERIC NOT NULL,
  url VARCHAR NULL,
  name VARCHAR NULL,
  summary VARCHAR NULL,
  space VARCHAR NULL,
  description VARCHAR NULL,
  experiences_offered VARCHAR NULL,
  neighborhood_overview VARCHAR NULL,
  notes VARCHAR NULL,
  transit VARCHAR NULL,
  access VARCHAR NULL,
  interaction VARCHAR NULL,
  house_rules VARCHAR NULL,
  thumbnail_url VARCHAR NULL,
  medium_url VARCHAR NULL,
  picture_url VARCHAR NULL,
  xl_picture_url VARCHAR NULL,
  street VARCHAR NULL,
  neighbourhood NUMERIC NULL,
  neighbourhood_cleansed NUMERIC NULL,
  neighbourhood_group_cleansed NUMERIC NULL,
  city VARCHAR NULL,
  state VARCHAR NULL,
  zipcode NUMERIC NULL,
  market VARCHAR NULL,
  country_code VARCHAR NULL,
  country VARCHAR NULL,
  latitude NUMERIC NULL,
  longitude NUMERIC NULL,
  is_location_exact BOOLEAN NULL,
  property_type VARCHAR NULL,
  room_type VARCHAR NULL,
  accommodates NUMERIC NULL,
  bathrooms NUMERIC NULL,
  bedrooms NUMERIC NULL,
  beds NUMERIC NULL,
  bed_type VARCHAR NULL,
  amenities VARCHAR NULL,
  square_feet NUMERIC NULL,
  price NUMERIC NULL,
  weekly_price NUMERIC NULL,
  monthly_price NUMERIC NULL,
  security_deposit NUMERIC NULL,
  cleaning_fee NUMERIC NULL,
  guests_included NUMERIC NULL,
  extra_people NUMERIC NULL,
  minimum_nights NUMERIC NULL,
  maximum_nights NUMERIC NULL,
  minimum_minimum_nights NUMERIC NULL,
  maximum_minimum_nights NUMERIC NULL,
  minimum_maximum_nights NUMERIC NULL,
  maximum_maximum_nights NUMERIC NULL,
  minimum_nights_avg_ntm NUMERIC NULL,
  maximum_nights_avg_ntm NUMERIC NULL,
  calendar_updated VARCHAR NULL,
  has_availability BOOLEAN NULL,
  availability_30 NUMERIC NULL, 
  availability_60 NUMERIC NULL,
  availability_90 NUMERIC NULL,
  availability_365 NUMERIC NULL,
  number_of_reviews NUMERIC NULL,
  number_of_reviews_ltm NUMERIC NULL,
  first_review VARCHAR NULL,
  last_review VARCHAR NULL,
  review_scores_rating NUMERIC NULL,
  review_scores_accuracy NUMERIC NULL,
  review_scores_cleanliness NUMERIC NULL,
  review_scores_checkin NUMERIC NULL,
  review_scores_communication NUMERIC NULL,
  review_scores_location NUMERIC NULL,
  review_scores_value NUMERIC NULL,
  requires_license BOOLEAN NULL,
  instant_bookable BOOLEAN NULL,
  is_business_travel_ready BOOLEAN NULL,
  cancellation_policy VARCHAR NULL,
  require_guest_profile_picture BOOLEAN NULL,
  require_guest_phone_verification BOOLEAN NULL,
  calculated_host_listings_count NUMERIC NULL,
  calculated_host_listings_count_entire_homes NUMERIC NULL,
  calculated_host_listings_count_private_rooms NUMERIC NULL,
  calculated_host_listings_count_shared_rooms NUMERIC NULL,
  reviews_per_month NUMERIC NULL);

CREATE TABLE host(
  id SMALLINT NOT NULL,
  listing_id SMALLINT NOT NULL,
  url VARCHAR NULL,
  name VARCHAR NOT NULL,
  since DATE NOT NULL,
  city VARCHAR NULL,
  neighborhood VARCHAR NULL,
  country VARCHAR NULL,
  about VARCHAR NULL,
  response_time VARCHAR NULL,
  response_rate SMALLINT NULL,
  acceptance_rate SMALLINT NULL,
  is_superhost BOOLEAN NULL,
  thumbnail_url VARCHAR NULL,
  picture_url VARCHAR NULL,
  neighbourhood VARCHAR NULL,
  listings_count SMALLINT NULL,
  total_listings_count SMALLINT NULL,
  verifications VARCHAR NULL,
  has_profile_pic BOOLEAN NULL,
  identity_verified BOOLEAN NULL);

CREATE TABLE calendar(
<<<<<<< HEAD
  id INT NOT NULL,
=======
  id SERIAL NOT NULL,
>>>>>>> routes
  listing_id INT NOT NULL,
  available BOOLEAN NOT NULL,
  date DATE NULL,
  price SMALLINT NOT NULL,
  adjusted_price SMALLINT NOT NULL,
  minimum_nights SMALLINT NOT NULL,
  maximum_nights SMALLINT NOT NULL);

